eu-digital-identity-wallet/eudi-lib-ios-rqes-ui

- Sources/Domain/Interactor/RQESInteractor.swift
- Sources/Infrastructure/Config/EudiRQESUiConfig.swift
- Sources/Infrastructure/EudiRQESUi.swift
- Sources/Presentation/UI/ServiceSelection/ServiceSelectionViewModel.swift
- Tests/Mock/GeneratedMocks.swift
Various improvements regarding RQESConfig
> Various improvements regarding RQESConfig

- Sources/Infrastructure/EudiRQESUi.swift
- Sources/Presentation/UI/Component/CardView.swift
> UI and Logic corrections

- Sources/Presentation/UI/SignedDocument/SignedDocumentView.swift
Add a description of the change here
> verified badge at document name

- Package.swift
> Updated to Latest RQESKit

- Sources/Presentation/UI/Component/ContentScreenView.swift
- Sources/Presentation/UI/Component/WrapButtonView.swift
- Sources/Presentation/UI/DocumentView/DocumentView.swift
- Sources/Presentation/UI/SignedDocument/SignedDocumentView.swift
> Ui Corrections

- Sources/Presentation/UI/DocumentView/DocumentView.swift
Minor correction for PDF Viewer
> Minor correction for PDF Viewer

- README.md
> Library Readme first part

- Package.swift
- Sources/Domain/Interactor/RQESInteractor.swift
Updated to latest version of rQES kit which has removed the signing algorithm configuration.
>  Updated rqes kit to 0.0.3

- Sources/Domain/Interactor/RQESInteractor.swift
- Sources/Infrastructure/Config/RqesServiceConfig.swift
Removed signing algorithm from configuration
> Configuration update

- Sources/Domain/Interactor/RQESInteractor.swift
…iple formats.
Retrieve the fileExtension and pass it to the RQESKit to support multiple formats
> Retrieve the fileExtension and pass it to the RQESKit to support multiple formats

- README.md
> Added How to use readme info

- Package.swift
> Updated rqes kit to 0.0.4

- Package.swift
> RQESKit Update

- Sources/Presentation/UI/CredentialSelection/CredentialSelectionViewModel.swift
Minor correction for DocumenName Certificate Selection Screen
> Minor correction for DocumenName Certificate Selection Screen

- .github/workflows/build-package.yml
- .github/workflows/dependencycheck.yml
- .github/workflows/gitleaks.yml
- .github/workflows/sonar.yml
> GitHub actions

- fastlane/Fastfile
Resolved issue with CI build workflow for external macros.
> Resolved issue with CI build workflow for external macros.

- Sources/Domain/Entities/SessionData.swift
- Sources/Domain/Interactor/RQESInteractor.swift
- Sources/Infrastructure/EudiRQESUi.swift
- Sources/Presentation/UI/CredentialSelection/CredentialSelectionViewModel.swift
- Sources/Presentation/UI/DocumentSelectionView/DocumentSelectionViewModel.swift
- Sources/Presentation/UI/DocumentView/DocumentViewModel.swift
- Sources/Presentation/UI/SignedDocument/SignedDocumentViewModel.swift
- Tests/Domain/Controller/TestLocalizationController.swift
- Tests/Domain/Interactor/TestRQESInteractor.swift
- Tests/Extension/EudiRQESUi.State+Extensions.swift
- Tests/Infrastructure/TestEudiRQESUi.swift
- Tests/Mock/GeneratedMocks.swift
- Tests/Util/TestConstants.swift
- fastlane/.xcovignore
Test cases for EudiRQESUi Actor, code improvements
> Test cases for EudiRQESUi Actor, code improvements

- Tests/Util/TestConstants.swift
> Correction for TestConstants

- Sources/Presentation/UI/CredentialSelection/CredentialSelectionViewModel.swift
- Sources/Presentation/UI/ServiceSelection/ServiceSelectionViewModel.swift
Fixed error state for Service and Credential Selection when RQESService returns error
> Fixed error state for Service and Credential Selection when RQESService returns error

- Sources/Presentation/UI/CredentialSelection/CredentialSelectionViewModel.swift
- Sources/Presentation/UI/ServiceSelection/ServiceSelectionViewModel.swift
Fixed loading state for Credentials and Services selection
> Fixed loading state for Credentials and Services selection

- Sources/Infrastructure/Theme/ColorManager.swift
correction for background color retrieval from assets
> correction for background color retrieval from assets

- Sources/Domain/Entities/Localization/LocalizableKey.swift
> Service error msg correction

- .gitignore
- Package.resolved
Package resolved should be tracked
> Package resolved should be tracked

- Sources/Domain/Entities/SessionData.swift
- Sources/Domain/Interactor/RQESInteractor.swift
- Sources/Infrastructure/EudiRQESUi.swift
- Sources/Presentation/UI/CredentialSelection/CredentialSelectionView.swift
- Sources/Presentation/UI/CredentialSelection/CredentialSelectionViewModel.swift
Resolved the issue with CredentialInfo retrieval once the authorization code was consumed.
> Resolved the issue with CredentialInfo retrieval once the authorization code was consumed.

- Sources/Domain/Interactor/RQESInteractor.swift
- Sources/Presentation/UI/ServiceSelection/ServiceSelectionView.swift
- Sources/Presentation/UI/ServiceSelection/ServiceSelectionViewModel.swift
- Tests/Mock/GeneratedMocks.swift
Resolved Issue with QTSP Selection
> Resolved Issue with QTSP Selection

- .gitignore
- fastlane/.env.dev
- fastlane/.env.release
- fastlane/Fastfile
- fastlane/README.md
Fastlane: Github release implementation
> Fastlane: Github release implementation

- Package.resolved
- Package.swift
> Dependencies update

- Package.resolved
> Maintenance update

- Sources/Presentation/UI/Component/ContentHeader/AppIconAndTextView.swift
- Sources/Presentation/UI/Component/ContentHeader/ContentHeaderView.swift
- Sources/Presentation/UI/Component/ContentHeader/RelyingPartyView.swift
- Sources/Presentation/UI/Component/SelectionItem/SelectionItemView.swift
- Sources/Presentation/UI/Component/WrapTextView.swift
- Sources/Presentation/UI/DocumentSelectionView/DocumentSelectionView.swift
- Tests/Domain/Controller/TestLocalizationController.swift
- Tests/Infrastructure/TestEudiRQESUi.swift
Refactor unit test names and view components
> Refactor unit tests names and view components

- README.md
- Sources/Domain/Entities/QTSPData.swift
- Sources/Domain/Interactor/RQESInteractor.swift
- Sources/Presentation/UI/ServiceSelection/ServiceSelectionView.swift
- Tests/UI/ViewModel/DocumentSelection/TestDocumentSelectionViewModel.swift
- Tests/UI/ViewModel/ServiceSelection/TestServiceSelectionViewModel.swift
- Tests/UI/ViewModel/SignedDocument/TestSignedDocumentViewModel.swift
- Tests/Util/TestConstants.swift
> Added tsaUrl to QTSP Config

- Package.resolved
- Package.swift
- README.md
- Sources/Domain/Controller/RQESController.swift
- Sources/Domain/Entities/QTSPData.swift
- Sources/Domain/Interactor/RQESInteractor.swift
- Sources/Presentation/UI/ServiceSelection/ServiceSelectionView.swift
- Tests/Domain/Interactor/TestRQESInteractor.swift
- Tests/Mock/GeneratedMocks.swift
- Tests/UI/ViewModel/CredentialSelection/TestCredentialSelectionViewModel.swift
- Tests/UI/ViewModel/Document/TestDocumentViewModel.swift
- Tests/UI/ViewModel/DocumentSelection/TestDocumentSelectionViewModel.swift
- Tests/UI/ViewModel/ServiceSelection/TestServiceSelectionViewModel.swift
- Tests/UI/ViewModel/SignedDocument/TestSignedDocumentViewModel.swift
- Tests/Util/TestConstants.swift
> Updated WalletKit to 0.3.1, resolved breaking changes

- Package.resolved
- Package.swift
> WalletKit 0.3.2 version

- Package.resolved
- Package.swift
> Updated Copyable Macro to latest version

- Package.resolved
- Package.swift
- Sources/Domain/DI/Assembly/ControllerAssembly.swift
- Sources/Domain/DI/Assembly/InteractorAssembly.swift
- Sources/Domain/Interactor/RQESInteractor.swift
- Sources/Infrastructure/EudiRQESUi.swift
- Sources/Presentation/Architecture/ViewModel.swift
> Swift 6.2 Support and Xcode 26, RQES Kit Update
